### ISSUE TITLE
Testing iptables checkpoint with bootkube

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/kenc#33]
Attach plan:
- [x] Run `kenc` container within apiserver pod
  - have init container for `kenc -r`
  -  **Assumption:** The pod has `hostNetwork=true`
  - need priviledged mode to run `iptables`, write to `hostPath` volume
  - mount hostPath volume to persist state
- [x] Use bootkube to start self-hosted k8s cluster with self hosted etcd
  - **Assumption:** There are two nodes, one master and one worker.
- [x] Restart master node (esp. apiserver); Check if k8s cluster comes back to health.

**Comment by hongchaodeng** [comment]
cc @xiang90 @aaronlevy

**Comment by hongchaodeng** [comment]
Tested

**Comment by hongchaodeng** [comment]
**Update**: also tested `kenc` as daemonset:
```
apiVersion: "extensions/v1beta1"
kind: DaemonSet
metadata:
  name: kenc
  namespace: kube-system
  labels:
    k8s-app: kenc
spec:
  template:
    metadata:
      labels:
        k8s-app: kenc
      annotations:
        checkpointer.alpha.coreos.com/checkpoint: "true"
    spec:
      nodeSelector:
        master: "true"
      hostNetwork: true
      containers:
      - image: gcr.io/coreos-k8s-scale-testing/kenc
        name: kenc
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/kubernetes/selfhosted-etcd
          name: checkpoint-dir
        command:
        - "/bin/sh"
        - "-c"
        - "kenc -r -m iptables && kenc -m iptables"
      volumes:
      - name: checkpoint-dir
        hostPath:
          path: /etc/kubernetes/selfhosted-etcd # default checkpoint data dir

```
